export const apiRoute = {
  seeker: "/user",
  getUserByID: "/getUserById",
  updateUserProfile: "/updateUserProfile",
  forgotPassword: "/forgotPassword",
  resetPassword: "/resetPassword",
  login: "/login",
  users: "/api/users",
  signUp: "/register",
  submitImage:'/submitImage',
  getHistory:'/getHistory',
  getRecruiterUsers: "/recruiters-list",
  getSingleRecruiter: "/single-recruiter",
  createMember: "/admin/createMember",
  updateRecruiter: "/admin/updateRecruiter",
  deleteRecruiter: "/admin/deleteRecruiter",
  updateStatus: "/admin/updateRecruiterStatus",
  getAdminUsers: "/admins-list",
  getSingleAdmin: "/single-admin",
  createAdmin: "/admin/createAdmin",
  updateAdmin: "/admin/updateAdmin",
  deleteAdmin: "/admin/deleteAdmin",
  getRecruitedUsers: "/recruitedUser-list",
  deleteRecruitedUser: "/recruiter/deleteRecruitedUser",
  getSingleRecruitedUser: "/single-recruitedUser",
  getSingleJobApplicant: "/single-recruitedUser",
  updateRecruitedUserStatus: "/recruiter/updateRecruitedUserStatus",
  updateJobApplicantStatus: "/recruiter/updateRecruitedUserStatus",
  createRecruitedUser: "/recruiter/createRecruitedUser",
  updateRecruitedUser: "/recruiter/updateRecruitedUser",
  getJobSeekers: "/getJobSeekerMembers",
  createRecruiterJob: "/recruiter/createRecruiterJob",
  getRecruiterJobs: "/recruiterJob-list",
  deleteRecruiterJob: "/recruiter/deleteRecruiterJob",
  getSingleRecruiterJob: "/single-recruiterJob",
  updateRecruiterJob: "/recruiter/updateRecruiterJob",
};
